<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('salons', function (Blueprint $table) {
            $table->id();

            /*
            |--------------------------------------------------------------------------
            | Basic Information
            |--------------------------------------------------------------------------
            */

            $table->string('name');

            /*
             * Public immutable code.
             * This code is used by the public URL and QR.
             *
             * Example:
             * SALON-X8K92
             */
            $table->string('code', 40)
                ->unique();

            $table->text('description')
                ->nullable();


            /*
            |--------------------------------------------------------------------------
            | Contact
            |--------------------------------------------------------------------------
            */

            $table->string('phone', 30)
                ->nullable();

            $table->string('email')
                ->nullable();


            /*
            |--------------------------------------------------------------------------
            | Branding
            |--------------------------------------------------------------------------
            */

            $table->string('logo_path')
                ->nullable();

            $table->string('cover_path')
                ->nullable();

            $table->string('primary_color', 20)
                ->nullable();

            $table->string('secondary_color', 20)
                ->nullable();


            /*
            |--------------------------------------------------------------------------
            | Address
            |--------------------------------------------------------------------------
            */

            $table->string('province', 100)
                ->nullable();

            $table->string('city', 100)
                ->nullable();

            $table->string('district', 100)
                ->nullable();

            $table->text('address')
                ->nullable();


            /*
            |--------------------------------------------------------------------------
            | Map / Location
            |--------------------------------------------------------------------------
            */

            $table->decimal('latitude', 10, 7)
                ->nullable();

            $table->decimal('longitude', 10, 7)
                ->nullable();


            /*
            |--------------------------------------------------------------------------
            | Existing QR
            |--------------------------------------------------------------------------
            |
            | QR is already generated by your BarberBook logic.
            | We only keep its stored file/path here.
            |
            */

            $table->string('qr_code_path')
                ->nullable();


            /*
            |--------------------------------------------------------------------------
            | Manager Barber
            |--------------------------------------------------------------------------
            |
            | We intentionally DO NOT create the foreign key here.
            | The barbers table is created later in migration order.
            |
            */

            $table->unsignedBigInteger('manager_barber_id')
                ->nullable()
                ->index();


            /*
            |--------------------------------------------------------------------------
            | Created By
            |--------------------------------------------------------------------------
            |
            | The Super Admin who created this salon.
            |
            */

            $table->foreignId('created_by')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete();


            /*
            |--------------------------------------------------------------------------
            | Status
            |--------------------------------------------------------------------------
            */

            $table->boolean('is_active')
                ->default(true)
                ->index();


            /*
            |--------------------------------------------------------------------------
            | Timestamps / Soft Delete
            |--------------------------------------------------------------------------
            */

            $table->timestamps();

            $table->softDeletes();
        });
    }


    public function down(): void
    {
        Schema::dropIfExists('salons');
    }
};
